ind={"ÁLGEBRA LINEAL", " CÁLCULO DIFERENCIAL"," CÁLCULO INTEGRAL","CÁLCULO MULTIVARIADO","ECUACIONES DIFERENCIALES","FUNDAMENTOS ELECTRONICA", "FÍSICA (MECANICA)", "FÍSICA OPTICA Y ONDAS", "FÍSICA ELECTRICIDAD",
"PENSAMIENTO ALGORÍTMICO", "PROGRAMACIÓN I", "PROGRAMACIÓN II", "Operaciones en ingenieria", "Análisis de datos", "Modelación de operaciones",  "Control de procesos", "Automatización de procesos",
"Diseño de instalaciones industriales", "MATEMATICAS DISCRETAs", "Fundamentos de Economía","Ingenieria Economica y financiera", 
"Formulacion y evaluación de proyectos", "PENSAMIENTO SISTEMICO Y AUTOMATIZACION","Prospectiva estrategica", "Control y aseguramiento de calidad",
"Sistemas integrados", "Gestión talento Humano"," FUNDAMENTOS DE INGENIERÍA", "ESTADÍSTICA,PROBABILIDAD E INFERENCIA", "Ingeniería de métodos",
"Planeación y programación de operaciones","Gestión de la cadena de abastecimiento","Logística de distribución y transporte","Diseño de sistemas logisticos",	"Simulación en Ingenieria", "PROFUNDIZACION I" ,"PROFUNDIZACION II","RAZONAMIENTO LOGICO Y CUANTITATIVO","COMUNICACIÓN Y LECTURA CRITICA I","CIUDADANIA DEL SIGLO 21",
"COMUNICACIÓN Y LECTURA CRITICA II", "LENGUA EXTRANJERA I", "LENGUA EXTRANGERA II", "LENGUA EXTRANGERA III", "CIENCIA TECNOLOGIA E INNOVACION", "CATEDRA GENERACION DEL SIGLO 21", "EMPRENDIMIENTO", "LENGUA EXTRANGERA IV", "INNOVACIÓN"}
soft={"ÁLGEBRA LINEAL","CÁLCULO DIFERENCIAL", "CÁLCULO INTEGRAL", "CÁLCULO MULTIVARIADO", "ECUACIONES DIFERENCIALES", "ANALISIS NUMERICO", "PENSAMIENTO ALGORÍTMICO", "PROGRAMACIÓN I", "PROGRAMACIÓN II", "PROGRAMACION WEB", "DESARROLLO NATIVO PARA DISPOSITIVOS MOVILES", "DESARROLO DE SOFTWARE PARA SISTEMAS HIBRIDOS", "DESARROLO DE SOFTWARE PARA SISTEMAS IOT", "REFACTORIZACION DE SOFTWARE", "METRICAS DE CALIDAD DE SOFTWARE", "FUNDAMENTOS DE ELECTRONICA",  "FÍSICA (MECANICA)",  "FÍSICA OPTICA Y ONDAS",
      "ESTRUCTURA DE DATOS","SISTEMAS OPERATIVOS","AUDITORIA DE SOFTWARE", "ANALISIS CONTROL Y SEGURIDAD DEL SOFTWARE", "FUNDAMENTOS DE INGENIERÍA", "ESTADÍSTICA,PROBABILIDAD E INFERENCIA", "REQUERIMIENTOS DE SOFTWARE", "INTERFAZ HOMBRE MAQUINA", "VIRTUALIZACION", "MODELAMIENTO DE SOFTWARE", "PATRONES EN DISEÑO DE SOFTWARE", "MATEMATICAS DISCRETAs", "ARQUITECTURA DE HARDWARE Y SOFTWARE", "SEGURIDAD INFORMATICA", "PROFUNDIZACION I", "CIENCIAS DE DATOS SOFTWARE SEGURO Y DE CALIDAD", "PENSAMIENTO SISTEMICO Y AUTOMATIZACION","RAZONAMIENTOLOGICO Y CUANTITATIVO","COMUNICACIÓN Y LECTURA CRITICA I", "CIUDADANIA DEL SIGLO 21", "COMUNICACIÓN Y LECTURA CRITICA II", "LENGUA EXTRANJERA I", "DISEÑO MODELACION BASES DE DATOS", "MOTORES GESTORES BASOS DE DATOS", "PROGRAMACION Y ADMINISTRACION EN BASES DE DATOS", "ARQUITECTURA DE DATOS", "DA TAMINING", "DA TAMINING INDUSTRIAS CREATIVAS",
      "LENGUA EXTRANGERA II", "LENGUA EXTRANGERA III",  "CATEDRA GENERACION DEL SIGLO 21", "CATEDRA GENERACION DEL SIGLO 21", "EMPRENDIMIENTO", "INNOVACIÓN", "DESARROLLO DE CONTENIDOS DIGITALES ", "TRABAJO DE GRADO"}
print("industrial",ind)
print("software",soft)

union=ind|soft
print(f"la union es {union}")

inter=ind&soft
print(f"interseccion es {inter}")

diferencia=ind-soft
print(f"diferencia es {diferencia}")

difsimetrica=ind^soft
print(f" diferencia simetrica es {ind^soft}")